### ISSUE TITLE
modulde 01 ex01 hatalı dosya

### ISSUE THREAD

**Issue by Bersarks** [burak-yldrm/Cpp#1]
Dosya isimlerinden ZombieHord.cpp olan ZombieHorde.cpp olması gerekli.

**Comment by burak-yldrm** [comment]
Bilgilendirme için teşekkürler, belirttiğin hatayı düzelttim.

**Comment by burak-yldrm** [comment]
Bilgilendirme için teşekkürler, belirttiğin hatayı düzelttim.

**Comment by burak-yldrm** [comment]
Bilgilendirme için teşekkürler, belirttiğin hatayı düzelttim.
